services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123

  web:
    build: .
    command: python Task_manager_Django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db